apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: shipt-routing
  labels:
    app: postgres
    app.kubernetes.io/part-of: shipt-routing-engine
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: shipt
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: routing-engine-secrets
                  key: DATABASE_URL
            - name: POSTGRES_DB
              value: shipt_routing
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: routing-engine-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "shipt", "-d", "shipt_routing"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "shipt", "-d", "shipt_routing"]
            initialDelaySeconds: 15
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: shipt-routing
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
